# Generated by Django 2.2.13 on 2020-06-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email ID')),
                ('contact', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contact Number')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date')),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False, verbose_name='Active User')),
                ('staff', models.BooleanField(default=False, verbose_name='Staff User')),
                ('admin', models.BooleanField(default=False, verbose_name='Superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
