# Generated by Django 2.2.13 on 2020-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nurseryshop', '0002_nursery_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='category',
            field=models.CharField(choices=[('Flower Plants', 'Flower Plants'), ('Trees', 'Trees'), ('Climbers', 'Climbers'), ('Creepers', 'Creepers')], default=None, max_length=20, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
