# Generated by Django 2.2.13 on 2020-06-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nurseryshop', '0003_plants_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.AddField(
            model_name='nursery',
            name='contact',
            field=models.CharField(default=None, max_length=10, verbose_name='Contact Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plants',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Nurseryshop.Category', verbose_name='Category'),
        ),
    ]
