# Generated by Django 2.2.13 on 2020-06-10 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nurseryshop', '0004_auto_20200609_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('checkout_date', models.DateField(verbose_name='Checkout Date')),
                ('status', models.IntegerField(choices=[(0, 'In Cart'), (1, 'Order Placed')], verbose_name='Status of order')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nurseryshop.Plants', verbose_name='Plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
