# Generated by Django 2.2.13 on 2020-06-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nurseryshop', '0005_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
    ]
